### ISSUE TITLE
Drobo FS wont start after install! "Your Drobo is in the starting phase, it will take a few secons" (Ihr drobo befindet sich in der Startphase ....)

### ISSUE THREAD

**Issue by BR0KK** [droboports/proftpd#1]
Both my drobo fs are in the latest firmware and right after installing this app both of them are not booting completely. 

I dont have control over my drobos anymore. All options are graed out. 

The Proftp is reachable and so are my shares?

**Comment by ricardopadilha** [comment]
If you can still mount shares, you can mount \\drobofs\DroboApps and delete the proftpd folder. Reboot the device and you should be able to manage your Drobos again.

**Comment by BR0KK** [comment]
Tried that and even after deleting the folder and rebooting the issue persists. I needed to take out all the drives, reboot and reflash the firmware. After the second reboot I powered down the drobos and inserted all disks again. 
Both drobos start normally after that. 

As far as my research got me, the problem cam be caused by a process hogging resources. 

I haven't tried to ssh into the drobos yet.
